#!/bin/sh
#
# This file is managed by Puppet via the "<%= @module_name %>" module.

# Logging levels:
EMERG=0
ALERT=1
CRIT=2
ERR=3
WARNING=4
NOTICE=5
INFO=6
DEBUG=7


say() {
    # Output a message with a priority prefix recognized by systemd-cat.
    local level=$1; shift
    printf '<%%s>%s\n' $level "$@"
}

crit() {
    # Convenience function for say() at the CRITICAL priority level.
    say $CRIT "$@"
}

err() {
    # Convenience function for say() at the ERROR priority level.
    say $ERR "$@"
}

info() {
    # Convenience function for say() at the INFORMATION priority level.
    say $INFO "$@"
}

fail() {
    # Issue a message at the ERROR priority level and quit, returning
    # a non-success exit code.
    err "$@"
    exit 1
}

config_lines() {
    # Return, via stdout, lines within the specified configuration file that
    # are not comments nor empty lines nor lines consisting of nothing more
    # than whitespace.  In other words, the actual active configuration
    # content.
    local config="$1"
    grep -Ev '^[[:space:]]*#|^[[:space:]]*$' $config
}
